# Generated by Django 4.2.1 on 2023-05-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_preentrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auto',
            new_name='autos',
        ),
        migrations.RenameField(
            model_name='autos',
            old_name='año',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='bicicletas',
            old_name='año',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='camiones',
            old_name='año',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='camionetas',
            old_name='año',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='motos',
            old_name='año',
            new_name='ano',
        ),
    ]
